version: "2"

linters:
  enable:
    - errorlint
    - gocritic
    - misspell
    - revive
    - unconvert
    - unparam
    - bodyclose
    - contextcheck
    - nilerr
    - noctx
  settings:
    revive:
      rules:
        - name: exported
        - name: package-comments

formatters:
  enable:
    - gofmt
    - goimports
