name: Feature request
description: Suggest an idea or improvement
labels: ["enhancement", "triage"]
body:
  - type: textarea
    id: problem
    attributes:
      label: What problem are you trying to solve?
      description: Describe the use case first, then the solution you have in mind.
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Proposed solution
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
